language: node_js
sudo: required
dist: trusty
addons:
  browserstack:
    username: will369
    access_key:
      secure: gWRjjvS2p9iNI11hN/c3MDtha18cMC2h1dJF4SbSzbX7KzKFug1tq8HTHKxc2CXQX4EivU56fcHHZryI9vXHbBNbLPMFRfmqCx31y8fRnoj+dsUMkfnep5h8wkBlzTMesGHT9NtDsDfgIv+LGznEZAKbRqo8H68kBp+rzZGmGuBshku59svuvfsJo28mPqYzfZDUtL/GJyz8bt/f+jwccSNfrUw/6gTmNdvCmPnxVydTpmitdE+UHhwueViQCCrZKQELfi5EfnnQHCVjrG+1HWLIkxxzRanbJudiJQkyyyfqzTzuETEF4xBgTLHT+XwqCQS+FKps5vyYIFczBsyK9QmYY2vG0xsEJgMd/7TBB7yhemjTE1RkW2aVVkA9pB8S5bAYtNyWKKcS+JcDIwJu520HRAbG/HvIFcCySh48Hi1GdZGnzYbvkNWKLXdk3IhJ8JhpFY2eC5fsgSVvvgeG3hBsCkCdOs7KX382q62d/kovFiXK4hYmv1oYcIzHEsJhpRrf/bRQHxjzIBnRwkF3Adp78S97IR1sKZmbVlF2ZpQq6kJqkeJfaTZve4Fl8UhG5kNx6jtwQkOUSTu1+rg7jfBtcorzqhJ9Nnb9IXdGVFtiBBkzDe67U4h8x95a8kD4KQ2t72IZVt2wyMZcy7eNx1apMXOeUjn/eGTnLVFZMnI=
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
node_js:
- node
- '6'
install:
- npm install
- npm install -g polymer-cli
- polymer install
before_script:
- npm run lint
script:
- xvfb-run -s '-screen 0 1024x768x24' polymer test
- xvfb-run -s '-screen 0 1024x768x24' polymer build
notifications:
  slack:
    secure: F8PinqxcMBkpBiwjkz8163QeLEnDm9SoQAafz+hcDu3IcNv+Wq1kG3xtXzWppyILe9PgrIPTE4mt5iMqvZ8RvdQ9ZcK8JaQF7ajLcRn9jTAGoZqscXVhvAjc4VkP3HDeiw1RFOvIGu+apb2UPBbbZVxb9BCJP3oaczSHhshyMd3rhgilj2+OgtOhHcESQ1/93xjFpijyaI74zcaWY48jUZ0tDxOKj0CzpsMY8yJKTL2OY0J+6pkeaKAhguWeMgZbsVkgmyVPfkkFjDhJqzYt6VKhuM/JN9Ja9GAracZYMSiyf6LWNHzO4XLOiRAOXmqgO4WSVf/yRQr2WRuMged8TFjWNsGIpdXIPyh3YLdC1zVKXt7fuecV18Oo/LPODLoDPwgiWRAgvEcKzbpwhjjnVUJfTJ/Cu7lpLFORNLMmAeuSIhEBKg606L9pyFJ502zDCQfkxAUB0hhSF7UxamSMkZ/l2ys27MDj4BKX3E5Yx+apEvCEwvjWW8hROvZvPhxZbmkJzse+8iCe0CjR1wziWULNNwtIAdsQ/LG2+t3ZKiU/AI1I6FjszJQxD9UpB3IP2n2gUzgiWU06/MAiYhPoMVaKbM23o4rpzmgWkBG2UW6TPzWgHqy0cERVO+rEkGnZnAHiU2Sn49Ctc7eAfaK3cE5V9nQpe4w9pKhJMy1nLiA=
