language: node_js
dist: trusty
sudo: required
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "node"
cache:
  directories:
    - $HOME/.cache/bower
    - node_modules
install:
  - npm install -g polymer-cli
  - npm install
  - polymer install
before_script:
  - npm run lint
script:
  - xvfb-run npm run test
  - xvfb-run npm run test:integration
notifications:
  slack:
    secure: F8PinqxcMBkpBiwjkz8163QeLEnDm9SoQAafz+hcDu3IcNv+Wq1kG3xtXzWppyILe9PgrIPTE4mt5iMqvZ8RvdQ9ZcK8JaQF7ajLcRn9jTAGoZqscXVhvAjc4VkP3HDeiw1RFOvIGu+apb2UPBbbZVxb9BCJP3oaczSHhshyMd3rhgilj2+OgtOhHcESQ1/93xjFpijyaI74zcaWY48jUZ0tDxOKj0CzpsMY8yJKTL2OY0J+6pkeaKAhguWeMgZbsVkgmyVPfkkFjDhJqzYt6VKhuM/JN9Ja9GAracZYMSiyf6LWNHzO4XLOiRAOXmqgO4WSVf/yRQr2WRuMged8TFjWNsGIpdXIPyh3YLdC1zVKXt7fuecV18Oo/LPODLoDPwgiWRAgvEcKzbpwhjjnVUJfTJ/Cu7lpLFORNLMmAeuSIhEBKg606L9pyFJ502zDCQfkxAUB0hhSF7UxamSMkZ/l2ys27MDj4BKX3E5Yx+apEvCEwvjWW8hROvZvPhxZbmkJzse+8iCe0CjR1wziWULNNwtIAdsQ/LG2+t3ZKiU/AI1I6FjszJQxD9UpB3IP2n2gUzgiWU06/MAiYhPoMVaKbM23o4rpzmgWkBG2UW6TPzWgHqy0cERVO+rEkGnZnAHiU2Sn49Ctc7eAfaK3cE5V9nQpe4w9pKhJMy1nLiA=

