language: node_js
dist: trusty
sudo: required
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "node"
cache:
  directories:
    - $HOME/.cache/bower
    - node_modules
install:
  - travis_wait mvn install
  - npm install -g polymer-cli
  - npm install
  - polymer install
before_script:
  - npm run lint
script:
  - xvfb-run -s '-screen 0 1024x768x24' polymer test
  - xvfb-run -s '-screen 0 1024x768x24' polymer build